"""initial_schema_sqlite_compatible

Revision ID: 6743b8965c05
Revises: 20260604_193510
Create Date: 2026-06-04 22:04:21.507443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6743b8965c05'
down_revision = '20260604_193510'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_noun_details_word_id', table_name='noun_details')
    op.create_index(op.f('ix_noun_details_word_id'), 'noun_details', ['word_id'], unique=True)
    op.drop_index('ix_verb_details_word_id', table_name='verb_details')
    op.create_index(op.f('ix_verb_details_word_id'), 'verb_details', ['word_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verb_details_word_id'), table_name='verb_details')
    op.create_index('ix_verb_details_word_id', 'verb_details', ['word_id'], unique=False)
    op.drop_index(op.f('ix_noun_details_word_id'), table_name='noun_details')
    op.create_index('ix_noun_details_word_id', 'noun_details', ['word_id'], unique=False)
    # ### end Alembic commands ###
